[book]
title        = "ESP32-C3 Wireless Adventure"
authors      = ["Espressif Systems"]
description  = "A comprehensive guide to IoT"
multilingual = false
language     = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/ZT-Pepite/esp32-c3-book-en"
mathjax-support = true
edit-url-template = "https://github.com/ZT-Pepite/test-c3-book/blob/main/TRANSLATIONS.md"
additional-js = ["custom.js"]